#!/bin/sh
// This script was automatically generated by SteamclEnv

echo "Writing .env file to root directory"

cd $CI_WORKSPACE/ci_scripts || exit 1

printf "API_URL=$API_URL=$" >> ../.env

echo "Wrote .env file."

exit 0
